### ISSUE TITLE
What is the difference between @import and <link> for CSS and which one is better?

### ISSUE THREAD

**Issue by gracejerios** [wwcodemanila/WWCodeManila-HTML.CSS#1]
According to this article **link** is preferred to **@import**, as it doesn't block parallel downloads. 
See this link for more details: http://www.stevesouders.com/blog/2009/04/09/dont-use-import/

In Summary:
Using @import within a stylesheet affect your page speed.
Using @import, files load sequentially (one has to wait for the other) instead of in parallel downloads.
Using @import in browser such as IE causes the download order to be altered.

**Comment by switmac** [comment]
thanks for this info Grace, now I know.. :) good find!

**Comment by azelalynetan** [comment]
Thanks Grace! I liked that you summarized it. Good job 👍
